### ISSUE TITLE
this.stream.clearLine is not a function

### ISSUE THREAD

**Issue by aiguanglee** [react-community/create-react-native-app#178]
Or enter this address in the Expo app's search bar:

  exp://192.168.1.7:19000

Your phone will need to be on the same local network as this computer.

For links to install the Expo app, please visit https://expo.io.

Logs from serving your app will appear here. Press Ctrl+C at any time to stop.

E:\workspace\react-native\weather-app\node_modules\.1.1.8@progress\lib\node-progress.js:177
    this.stream.clearLine();
                ^
TypeError: this.stream.clearLine is not a function
    at ProgressBar.terminate (E:\workspace\react-native\weather-app\node_modules\.1.1.8@progress\lib\node-progress.js:177:17)
    at ProgressBar.tick (E:\workspace\react-native\weather-app\node_modules\.1.1.8@progress\lib\node-progress.js:91:10)
    at PackagerLogsStream.onFinishBuildBundle [as _onFinishBuildBundle] (E:\workspace\react-native\weather-app\node_modules\.0.0.28@react-native-scripts\build\util\packager.js:123:21)
    at PackagerLogsStream._handleUpdateBundleTransformProgress.progressChunk [as _handleUpdateBundleTransformProgress] (E:\xdl\src\logs\PackagerLogsStream.js:187:16)
    at PackagerLogsStream._handleBundleTransformEvent.chunk [as _handleBundleTransformEvent] (E:\xdl\src\logs\PackagerLogsStream.js:135:14)
    at PackagerLogsStream._handlePackagerEvent.chunk [as _handlePackagerEvent] (E:\xdl\src\logs\PackagerLogsStream.js:101:12)
    at Object.write (E:\xdl\src\logs\PackagerLogsStream.js:82:18)
    at Logger._emit (E:\workspace\react-native\weather-app\node_modules\.1.8.10@bunyan\lib\bunyan.js:923:22)
    at Logger.info (E:\workspace\react-native\weather-app\node_modules\.1.8.10@bunyan\lib\bunyan.js:1045:24)
    at Object.logInfo (E:\xdl\src\project\ProjectUtils.js:92:29)
    at _logPackagerOutput (E:\xdl\src\Project.js:548:18)
    at Socket.<anonymous> (E:\xdl\src\Project.js:689:7)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)

**Comment by brentvatne** [comment]
Hello! Please follow the issue template when submitting an issue. In particular here, we need some information about your environment. Issue template is attached below.

--------------------------------------------------------------

Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior

What action did you perform, and what did you expect to happen?

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
* `npm ls react-native`:
* `npm ls expo`:
* `node -v`:
* `npm -v`:
* `yarn --version`:
* `watchman version`:

Also specify:

1. Operating system:
2. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by brentvatne** [comment]
Apparently this can happen in a Docker container, maybe also in git-bash. Maybe we want to update `progress` to 2.0.0 which apparently was released 18 days ago and guards against `clearLine` not being defined - https://github.com/visionmedia/node-progress/commit/8ef3972b5e29bd67bd1d55d21810ee4ac692d969

**Comment by aiguanglee** [comment]
## Description

When trying to open app in Expo, syntax error is thrown and process exits.

## Expected Behavior

Application normal operation

## Observed Behavior

E:\workspace\react-native\weather-app\node_modules.1.1.8@progress\lib\node-progress.js:177
this.stream.clearLine();
^
TypeError: this.stream.clearLine is not a function
at ProgressBar.terminate (E:\workspace\react-native\weather-app\node_modules.1.1.8@progress\lib\node-progress.js:177:17)
at ProgressBar.tick (E:\workspace\react-native\weather-app\node_modules.1.1.8@progress\lib\node-progress.js:91:10)

## Environment

Please run these commands in the project folder and fill in their results:

npm ls react-native-scripts:react-native-scripts@0.0.28
npm ls react-native: react-native@0.43.4
npm ls expo: expo@16.0.0
node -v: 7.6.0
npm -v: 4.1.2
yarn --version: 0.19.1
Also specify:

Operating system: windows 10

**Comment by brentvatne** [comment]
thanks @aiguanglee! this should be fixed with #179, when a new version is published

**Comment by dikaiosune** [comment]
Published a new version with @brentvatne's fix, please post here if it's still not fixed and I need to reopen this issue.

**Comment by yash2code** [comment]
@aiguanglee  same issue. How did you solved it?

**Comment by yash2code** [comment]
@dikaiosune  post the solution please

**Comment by dikaiosune** [comment]
@yash2code please update to the newest version of react-native-scripts, as indicated earlier in the message thread.

**Comment by yash2code** [comment]
@dikaiosune  whats the command to update?

**Comment by dikaiosune** [comment]
@yash2code I recommend reading about [package.json](https://docs.npmjs.com/files/package.json)

**Comment by yash2code** [comment]
@dikaiosune I kno about it but to which version to update? And will chnging version and npm update will do the trick?
