### ISSUE TITLE
bunyun errors after re-install dependencies

### ISSUE THREAD

**Issue by LeiZeng** [react-community/create-react-native-app#197]
## Description

After I create a new project, found some issue need to re-install all the dependencies, got some error for `bunyan` while `yarn start`

## Expected Behavior
```bash
$ create-react-native-app myApp
$ cd myApp && yarn start
// Works fine
$ rm -rf node_modules && yarn
$ yarn start
// Got error
```
It should still works if I re-install the dependencies.

## Observed Behavior
Following errors pop up.

```
yarn start v0.15.1
$ react-native-scripts start 

/Users/xxx/Workspace/react-native/myApp/node_modules/bunyan/lib/bunyan.js:607
        assert.ok(mv, '"rotating-file" stream type is not supported: '
               ^
AssertionError: "rotating-file" stream type is not supported: missing "mv" module
    at Logger.addStream (/Users/xxx/Workspace/react-native/myApp/node_modules/bunyan/lib/bunyan.js:607:16)
    at /Users/xxx/Workspace/react-native/myApp/node_modules/bunyan/lib/bunyan.js:470:18
    at Array.forEach (native)
    at new Logger (/Users/xxx/Workspace/react-native/myApp/node_modules/bunyan/lib/bunyan.js:469:25)
    at Function.createLogger (/Users/xxx/Workspace/react-native/myApp/node_modules/bunyan/lib/bunyan.js:1618:12)
    at Object.<anonymous> (/xdl/src/Logger.js:25:26)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: 0.0.29 
* `npm ls react-native`: 0.43.4
* `npm ls expo`: 16.0.0
* `node -v`: 6.1.0
* `npm -v`: 3.8.6
* `yarn --version`: 0.15.1
* `watchman version`: 4.7.0

Also specify:

1. Operating system: Mac OS 10.12.4
2. Phone/emulator/simulator & version: NAN

**Comment by brentvatne** [comment]
hello! please update your yarn version, 0.15.1 is very old! it is from october when it was first released and there have been many improvements since then. the current version is 0.24.5
