### ISSUE TITLE
Empty CRNA Project on Ubuntu failed to start

### ISSUE THREAD

**Issue by nsisodiya** [react-community/create-react-native-app#208]
I created a project from CRNA. It is working good on Mac, but On Ubuntu, it is failing to start.

```
 yarn start
yarn start v0.24.4
$ react-native-scripts start 
9:18:53 PM: Starting packager...

/xdl/src/logs/PackagerLogsStream.js:100
    if (msg.type.match(/^bundle_/)) {
        ^
TypeError: Cannot read property 'match' of undefined
    at PackagerLogsStream._handlePackagerEvent.chunk [as _handlePackagerEvent] (/xdl/src/logs/PackagerLogsStream.js:100:9)
    at Object.write (/xdl/src/logs/PackagerLogsStream.js:82:18)
    at Logger._emit (/home/narendra/Billexo/billexo-merchant-app/node_modules/bunyan/lib/bunyan.js:923:22)
    at Logger.error (/home/narendra/Billexo/billexo-merchant-app/node_modules/bunyan/lib/bunyan.js:1045:24)
    at Object.logError (/xdl/src/project/ProjectUtils.js:107:29)
    at _logPackagerOutput (/xdl/src/Project.js:550:18)
    at Socket.<anonymous> (/xdl/src/Project.js:694:7)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
error Command failed with exit code 1.
```
Please help me debug what is the problem.

**Comment by brentvatne** [comment]
Hello! Can you share your project?

**Comment by brentvatne** [comment]
@nsisodiya - alternatively, can you share your app.json and package.json?

**Comment by nsisodiya** [comment]
@brentvatne 
Please find the app.json and package.json here  - https://gist.github.com/nsisodiya/098be8190ef448ac5fee560d90b5f2e8

**Comment by nsisodiya** [comment]
I have created an empty project and I am getting the error on the empty project too.

```
                    [~/Billexo]
$ create-react-native-app my-app
Creating a new React Native app in /home/narendra/Billexo/my-app.

Installing packages. This might take a couple minutes.
Installing react-native-scripts...

yarn add v0.24.4
info No lockfile found.
[1/4] Resolving packages...
warning react-native-scripts > fs-promise@1.0.0: Use mz or fs-extra^3.0 with Promise Support
warning react-native-scripts > xdl > @exponent/spawn-async@1.2.8: Please switch to @expo/spawn-async, the new name of this package. It's the same code with our new name.
warning react-native-scripts > xdl > @exponent/osascript > @exponent/spawn-async@1.2.8: Please switch to @expo/spawn-async, the new name of this package. It's the same code with our new name.
warning react-native-scripts > xdl > auth0-js > xtend > object-keys@0.4.0: 
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 308 new dependencies.
├─ @ccheever/crayon@5.0.0
├─ @exponent/json-file@5.3.0
├─ @exponent/ngrok@2.2.7
├─ @exponent/node-auth0@2.6.0
├─ @exponent/osascript@1.6.4
├─ @exponent/spawn-async@1.2.8
├─ @segment/loosely-validate-event@1.1.2
├─ abbrev@1.1.0
├─ accepts@1.3.3
├─ ajv@4.11.8
├─ analytics-node@2.4.1
├─ ansi-escapes@1.4.0
├─ ansi-regex@2.1.1
├─ ansi-styles@2.2.1
├─ any-promise@1.3.0
├─ array-flatten@1.1.1
├─ asap@2.0.5
├─ asn1@0.2.3
├─ assert-plus@1.0.0
├─ async@0.9.2
├─ asynckit@0.4.0
├─ auth0-js@7.6.1
├─ aws-sign2@0.6.0
├─ aws4@1.6.0
├─ babel-runtime@6.23.0
├─ balanced-match@0.4.2
├─ Base64@0.1.4
├─ base64url@2.0.0
├─ bcrypt-pbkdf@1.0.1
├─ binary@0.3.0
├─ block-stream@0.0.9
├─ bluebird@2.11.0
├─ body-parser@1.17.1
├─ boom@2.10.1
├─ brace-expansion@1.1.7
├─ buffer-equal-constant-time@1.0.1
├─ buffer-shims@1.0.0
├─ buffers@0.1.1
├─ bunyan@1.8.10
├─ bytes@2.4.0
├─ camel-case@1.2.2
├─ caseless@0.12.0
├─ chainsaw@0.1.0
├─ chalk@1.1.3
├─ change-case@2.3.1
├─ cli-cursor@2.1.0
├─ cli-width@2.1.0
├─ clone@2.1.1
├─ co@4.6.0
├─ combined-stream@1.0.5
├─ commander@2.9.0
├─ component-emitter@1.2.1
├─ component-type@1.2.1
├─ concat-map@0.0.1
├─ constant-case@1.1.2
├─ content-disposition@0.5.2
├─ content-type@1.0.2
├─ cookie-signature@1.0.6
├─ cookie@0.3.1
├─ cookiejar@2.1.1
├─ core-js@1.2.7
├─ core-util-is@1.0.2
├─ create-react-class@15.5.3
├─ cross-spawn@5.1.0
├─ cryptiles@2.0.5
├─ crypto-token@1.0.1
├─ dashdash@1.14.1
├─ debug@2.6.1
├─ decompress-zip@0.3.0
├─ deep-diff@0.3.4
├─ delay-async@1.1.0
├─ delayed-stream@1.0.0
├─ depd@1.1.0
├─ destroy@1.0.4
├─ dot-case@1.1.2
├─ dtrace-provider@0.8.1
├─ ecc-jsbn@0.1.1
├─ ecdsa-sig-formatter@1.0.9
├─ ee-first@1.1.1
├─ encodeurl@1.0.1
├─ encoding@0.1.12
├─ es6-error@4.0.2
├─ escape-html@1.0.3
├─ escape-string-regexp@1.0.5
├─ etag@1.8.0
├─ exec-async@2.2.0
├─ exists-async@2.0.0
├─ express@4.15.2
├─ extend@3.0.1
├─ external-editor@2.0.1
├─ extsprintf@1.0.2
├─ fbjs@0.8.12
├─ figures@2.0.0
├─ file-type@4.3.0
├─ finalhandler@1.0.2
├─ forever-agent@0.6.1
├─ form-data@2.1.4
├─ formidable@1.1.1
├─ forwarded@0.1.0
├─ freeport-async@1.1.1
├─ fresh@0.5.0
├─ fs-extra@0.30.0
├─ fs-promise@1.0.0
├─ fs.realpath@1.0.0
├─ fstream@1.0.11
├─ getpass@0.1.7
├─ glob@7.1.1
├─ graceful-fs@4.1.11
├─ graceful-readlink@1.0.1
├─ har-schema@1.0.5
├─ har-validator@4.2.1
├─ has-ansi@2.0.0
├─ has-color@0.1.7
├─ hasbin@1.2.3
├─ hawk@3.1.3
├─ hoek@2.16.3
├─ hoist-non-react-statics@1.2.0
├─ home-dir@1.0.0
├─ http-errors@1.6.1
├─ http-signature@1.1.1
├─ iconv-lite@0.4.15
├─ indent-string@3.1.0
├─ inflight@1.0.6
├─ inherits@2.0.3
├─ inquirer@3.0.6
├─ instapromise@2.0.7-rc.1
├─ invariant@2.2.2
├─ ip@1.1.5
├─ ipaddr.js@1.3.0
├─ is-fullwidth-code-point@2.0.0
├─ is-lower-case@1.1.3
├─ is-promise@2.1.0
├─ is-stream@1.1.0
├─ is-typedarray@1.0.0
├─ is-upper-case@1.1.2
├─ isarray@0.0.1
├─ isemail@2.2.1
├─ isexe@2.0.0
├─ isomorphic-fetch@2.2.1
├─ isstream@0.1.2
├─ items@2.1.1
├─ jodid25519@1.0.2
├─ joi@10.4.2
├─ join-component@1.1.0
├─ js-tokens@3.0.1
├─ jsbn@0.1.1
├─ json-fallback@0.0.1
├─ json-schema@0.2.3
├─ json-stable-stringify@1.0.1
├─ json-stringify-safe@5.0.1
├─ json5@0.5.1
├─ jsonfile@2.4.0
├─ jsonify@0.0.0
├─ jsonp@0.0.4
├─ jsonschema@1.1.1
├─ jsonwebtoken@7.4.0
├─ jsprim@1.4.0
├─ jwa@1.1.5
├─ jws@3.1.4
├─ klaw@1.3.1
├─ lock@0.1.3
├─ lodash-es@4.17.4
├─ lodash.once@4.1.1
├─ lodash@4.17.4
├─ loose-envify@1.3.1
├─ lower-case-first@1.0.2
├─ lower-case@1.1.4
├─ lru-cache@4.0.2
├─ match-require@2.1.0
├─ md5hex@1.0.0
├─ media-typer@0.3.0
├─ merge-descriptors@1.0.1
├─ methods@1.1.2
├─ mime-db@1.27.0
├─ mime-types@2.1.15
├─ mime@1.3.4
├─ mimic-fn@1.1.0
├─ minimatch@3.0.4
├─ minimist@1.2.0
├─ mkdirp-promise@5.0.1
├─ mkdirp@0.5.1
├─ mkpath@0.1.0
├─ moment@2.18.1
├─ mout@0.11.1
├─ ms@0.7.3
├─ mute-stream@0.0.7
├─ mv@2.1.1
├─ mz@2.6.0
├─ nan@2.6.2
├─ ncp@2.0.0
├─ negotiator@0.6.1
├─ node-fetch@1.6.3
├─ nopt@3.0.6
├─ oauth-sign@0.8.2
├─ object-assign@4.1.1
├─ object-keys@0.4.0
├─ on-finished@2.3.0
├─ once@1.4.0
├─ onetime@2.0.1
├─ opn@4.0.2
├─ os-tmpdir@1.0.2
├─ param-case@1.1.2
├─ parseurl@1.3.1
├─ pascal-case@1.1.2
├─ path-case@1.1.2
├─ path-exists@3.0.0
├─ path-is-absolute@1.0.1
├─ path-to-regexp@0.1.7
├─ performance-now@0.2.0
├─ pify@2.3.0
├─ pinkie-promise@2.0.1
├─ pinkie@2.0.4
├─ process-nextick-args@1.0.7
├─ progress@2.0.0
├─ promise-props@1.0.0
├─ promise@7.1.1
├─ prop-types@15.5.10
├─ proxy-addr@1.1.4
├─ pseudomap@1.0.2
├─ punycode@1.3.2
├─ q@1.5.0
├─ qrcode-terminal@0.11.0
├─ qs@6.4.0
├─ querystring@0.2.0
├─ range-parser@1.2.0
├─ raw-body@2.2.0
├─ react-native-scripts@0.0.29
├─ react-redux@5.0.4
├─ react@15.5.4
├─ read-chunk@2.0.0
├─ readable-stream@1.1.14
├─ redux-logger@2.10.2
├─ redux@3.6.0
├─ regenerator-runtime@0.10.5
├─ remove-trailing-slash@0.1.0
├─ request-progress@3.0.0
├─ request@2.81.0
├─ reqwest@2.0.5
├─ rest-facade@1.5.0
├─ restore-cursor@2.0.0
├─ rimraf@2.6.1
├─ run-async@2.3.0
├─ rx@4.1.0
├─ safe-buffer@5.0.1
├─ safe-json-stringify@1.0.4
├─ semver@5.3.0
├─ send@0.15.1
├─ sentence-case@1.1.3
├─ serve-static@1.12.1
├─ setimmediate@1.0.5
├─ setprototypeof@1.0.3
├─ shebang-command@1.2.0
├─ shebang-regex@1.0.0
├─ signal-exit@3.0.2
├─ slugid@1.1.0
├─ slugify@1.1.0
├─ snake-case@1.1.2
├─ sntp@1.0.9
├─ source-map-support@0.4.15
├─ source-map@0.5.6
├─ sshpk@1.13.0
├─ statuses@1.3.1
├─ string_decoder@0.10.31
├─ string-width@2.0.0
├─ stringstream@0.0.5
├─ strip-ansi@3.0.1
├─ superagent-retry@0.6.0
├─ superagent@3.5.2
├─ supports-color@2.0.0
├─ swap-case@1.1.2
├─ symbol-observable@1.0.4
├─ tar.gz@1.0.5
├─ tar@2.2.1
├─ thenify-all@1.6.0
├─ thenify@3.2.1
├─ throttleit@1.0.0
├─ through@2.3.8
├─ title-case@1.1.2
├─ tmp@0.0.31
├─ topo@2.0.2
├─ touch@0.0.3
├─ tough-cookie@2.3.2
├─ traverse@0.3.9
├─ tree-kill@1.1.0
├─ trim@0.0.1
├─ tunnel-agent@0.6.0
├─ tweetnacl@0.14.5
├─ type-is@1.6.15
├─ ua-parser-js@0.7.12
├─ unpipe@1.0.0
├─ upper-case-first@1.1.2
├─ upper-case@1.1.3
├─ url-join@0.0.1
├─ url@0.11.0
├─ util-deprecate@1.0.2
├─ utils-merge@1.0.0
├─ uuid@3.0.1
├─ vary@1.1.1
├─ verror@1.3.6
├─ whatwg-fetch@2.0.3
├─ which@1.2.14
├─ winchan@0.1.4
├─ wrappy@1.0.2
├─ xdl@40.0.0
├─ xhr2@0.1.4
├─ xtend@4.0.1
├─ yallist@2.1.2
└─ yesno@0.0.1
Done in 17.34s.
Installing dependencies using yarnpkg...

yarn install v0.24.4
[1/4] Resolving packages...
warning react-native > xcode > node-uuid@1.4.7: Use uuid module instead
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 78.44s.


Success! Created my-app at /home/narendra/Billexo/my-app
Inside that directory, you can run several commands:

  yarn start
    Starts the development server so you can open your app in the Expo
    app on your phone.

  yarn run ios
    (Mac only, requires Xcode)
    Starts the development server and loads your app in an iOS simulator.

  yarn run android
    (Requires Android build tools)
    Starts the development server and loads your app on a connected Android
    device or emulator.

  yarn test
    Starts the test runner.

  yarn run eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd my-app
  yarn start

Happy hacking!

                    [~/Billexo]
$ cd my-app/

                    [~/Billexo/my-app]
$ yarn start
yarn start v0.24.4
$ react-native-scripts start 
11:48:51 AM: Starting packager...

/xdl/src/logs/PackagerLogsStream.js:100
    if (msg.type.match(/^bundle_/)) {
        ^
TypeError: Cannot read property 'match' of undefined
    at PackagerLogsStream._handlePackagerEvent.chunk [as _handlePackagerEvent] (/xdl/src/logs/PackagerLogsStream.js:100:9)
    at Object.write (/xdl/src/logs/PackagerLogsStream.js:82:18)
    at Logger._emit (/home/narendra/Billexo/my-app/node_modules/bunyan/lib/bunyan.js:923:22)
    at Logger.error (/home/narendra/Billexo/my-app/node_modules/bunyan/lib/bunyan.js:1045:24)
    at Object.logError (/xdl/src/project/ProjectUtils.js:107:29)
    at _logPackagerOutput (/xdl/src/Project.js:550:18)
    at Socket.<anonymous> (/xdl/src/Project.js:694:7)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
error Command failed with exit code 1.

                    [~/Billexo/my-app]
$ 

```

**Comment by nsisodiya** [comment]
I have tried to debug it, seems like msg is not having the type attribute. following msg is breaking the things.
```
{ code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /home/narendra/Billexo/billexo-merchant-app/node_modules/lodash/fp',
  filename: '/home/narendra/Billexo/billexo-merchant-app/node_modules/lodash/fp' }
```
also
```
$ watch -v
watch from procps-ng 3.3.9
```

**Comment by nsisodiya** [comment]
I have resolved this issue my typing following command.

```
echo fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```
This fixed problem with my ubuntu machine.
Thanks.
