### ISSUE TITLE
Install "create-react-native-app" failed on Windows NPM

### ISSUE THREAD

**Issue by mathselse** [react-community/create-react-native-app#297]
I could not install "create-react-native-app" on Windows.

1. **Environment info**:
- OS: Windows 10
- Node: v8.1.3 (node v6.x also showed the same error)
- NPM: 5.0.3
- CMD as adminstrator

2. **Error**:
```
npm ERR! code EACCES
npm ERR! errno EACCES
npm ERR! FetchError: request to https://registry.npmjs.org/create-react-native-app failed, reason: connect EACCES 151.101.64.162:443
npm ERR!     at ClientRequest.req.on.err (C:\Users\mathselse\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at emitOne (events.js:115:13)
npm ERR!     at ClientRequest.emit (events.js:210:7)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:400:9)
npm ERR!     at emitOne (events.js:115:13)
npm ERR!     at TLSSocket.emit (events.js:210:7)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:62:8)
npm ERR!     at _combinedTickCallback (internal/process/next_tick.js:102:11)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:161:9)
npm ERR!  { FetchError: request to https://registry.npmjs.org/create-react-native-app failed, reason: connect EACCES 151.101.64.162:443
npm ERR!     at ClientRequest.req.on.err (C:\Users\mathselse\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at emitOne (events.js:115:13)
npm ERR!     at ClientRequest.emit (events.js:210:7)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:400:9)
npm ERR!     at emitOne (events.js:115:13)
npm ERR!     at TLSSocket.emit (events.js:210:7)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:62:8)
npm ERR!     at _combinedTickCallback (internal/process/next_tick.js:102:11)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:161:9)
npm ERR!   message: 'request to https://registry.npmjs.org/create-react-native-app failed, reason: connect EACCES 151.101.64.162:443',
npm ERR!   type: 'system',
npm ERR!   errno: 'EACCES',
npm ERR!   code: 'EACCES' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mathselseAppData\Roaming\npm-cache\_logs\2017-07-08T19_12_10_784Z-debug.log
```

Please help!
Thanks,

**Comment by brentvatne** [comment]
npm 5 isn't supported. the error message that you mention here is in the npm docs as a common problem :)

**Comment by joelGarcia93** [comment]
@brentvatne so, what's the solution? o.O

**Comment by brentvatne** [comment]
It's in getting started inside the readme, sorry not at a computer atm

**Comment by Ananthusubramanian** [comment]
why doesnt it have a solution.
