### ISSUE TITLE
create-react-native-app command hangs with Error

### ISSUE THREAD

**Issue by clintj42** [react-community/create-react-native-app#372]
## Description
When I run `create-react-native-app MyApp`, it runs for a while then gives me the following error: 

```
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit  expo/node-websql#18.0.0 resetting remote C:\Users\Clint\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expo-node-websql-git-18-0-0-17a6eb60 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
```

After that it just hangs in the terminal.

I'm using Windows 10 and git bash for Windows.

**Comment by brentvatne** [comment]
seems like a npm / git thing: https://stackoverflow.com/questions/31744852/npm-install-giving-error-while-accessing-git-url
