### ISSUE TITLE
Error while running npm (IgnorePattern is not a function)

### ISSUE THREAD

**Issue by asystat** [react-community/create-react-native-app#435]
Does anybody know what this error is and how can I fix it?

When I run 

> sudo npm start

```
Loading dependency graph...jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: ignorePattern is not a function. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.html.
 ERROR  ignorePattern is not a function
TypeError: ignorePattern is not a function
    at HasteMap._ignore (/Users/perroloco/Programming/Vivancar/a_guard/node_modules/jest-haste-map/build/index.js:774:5)
    at stdout.trim.split.filter.x (/Users/perroloco/Programming/Vivancar/a_guard/node_modules/jest-haste-map/build/crawlers/node.js:99:58)
    at Array.filter (native)
    at Socket.child.stdout.on (/Users/perroloco/Programming/Vivancar/a_guard/node_modules/jest-haste-map/build/crawlers/node.js:99:45)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
Loading dependency graph...npm ERR! code ELIFECYCLE
npm ERR! errno 11
npm ERR! a_guard@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 11
npm ERR!
npm ERR! Failed at the a_guard@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/perroloco/.npm/_logs/2017-10-12T18_31_52_008Z-debug.log
```

**Comment by dikaiosune** [comment]
Can you please complete the new issue template?

**Comment by brentvatne** [comment]
closed for no response
