### ISSUE TITLE
Error with sentry-expo

### ISSUE THREAD

**Issue by gurmeetsinghmalhotra** [react-community/create-react-native-app#511]
## Description

My app was working fine as expected then I ran "npm i sentry-expo --save" as per the documentation. Next I restarted my server to generate new qr code for my app in the terminal.

## Observed Behavior

I received the following error

```
collegedunia@collegedunia-HP-Notebook:/var/www/CDHRMS$ sudo npm start

> CDHRMS@0.1.0 start /var/www/CDHRMS
> react-native-scripts start

18:20:33: Starting packager...
***ERROR STARTING PACKAGER***

Error parsing JSON file: SyntaxError: Expected '}' instead of EOF at line 45 column 1 of the JSON5 data. Still to read: ""
18:20:34: Error starting packager: Error: Couldn't start project. Please fix the errors and restart the project.
    at /xdl/src/Project.js:1252:11
    at Generator.next (<anonymous>)
    at step (/var/www/CDHRMS/node_modules/xdl/build/Project.js:1632:191)
    at /var/www/CDHRMS/node_modules/xdl/build/Project.js:1632:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! CDHRMS@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the CDHRMS@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/collegedunia/.npm/_logs/2017-12-17T12_50_34_070Z-debug.log

```

## Environment

* `npm ls react-native-scripts`: react-native-scripts@1.8.1 
* `npm ls react-native`: react-native@0.50.3
* `npm ls expo`: expo@23.0.5
* `node -v`: v8.6.0
* `npm -v`: 4.6.1
* `yarn --version`: not installed
* `watchman version`: not installed

Also specify:

1. Operating system: Linux
2. Phone/emulator/simulator & version: Lenovo A7000-a

**Comment by gurmeetsinghmalhotra** [comment]
Sorry for the trouble there was an , missing in my app.json
