### ISSUE TITLE
UX: npm 5 error, yarn is not picked

### ISSUE THREAD

**Issue by bestander** [react-community/create-react-native-app#530]
## Description

I could not create a React Native app on my machine and it was not clear why.
Apparently it is package manager issues.

```
create-react-native-app MyRnApp
Creating a new React Native app in /Users/bestander/work/MyRnApp.

Using package manager as npm with npm interface.
Installing packages. This might take a couple minutes.
Installing react-native-scripts...

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-redux@5.0.6 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0 but none was installed.

+ react-native-scripts@1.8.1
added 423 packages in 18.72s

*******************************************************************************
ERROR: npm 5 is not supported yet
*******************************************************************************

It looks like you're using npm 5 which was recently released.

Create React Native App doesn't work with npm 5 yet, unfortunately. We
recommend using npm 4 or yarn until some bugs are resolved.

You can follow the known issues with npm 5 at:
https://github.com/npm/npm/issues/16991

*******************************************************************************

[09:43:27] bestander:~/work $ cat MyRnApp/package.json
{
  "name": "MyRnApp",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "1.8.1"
  }
}
```

## Expected Behavior

1. npm@5 problem is printed in yellow (as warning) and I had no idea that I have a corrupt installation with no clear way to recover it.
If the error is colored red and there is a guide how to recover (update npm, switch to yarn etc) it would work better for beginners like me

2. Would it be better to check for npm@5 issue before starting to bootstrap the project?

3. I have yarn installed but it was not picked by the app by default
I guess because it checks whether yarn is installed using
```
var result = _crossSpawn2.default.sync('yarnpkg', ['--version'], { stdio: 'ignore' });
```

Not all Yarn installations register `yarnpkg` bin.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@1.8.1
* `npm ls react-native`: react-native@0.50.3
* `npm ls expo`: expo@23.0.6
* `node -v`: v8.1.2
* `npm -v`: 5.0.3
* `yarn --version`: 1.2.0
* `watchman version`: watchman: command not found
 
Also specify:

1. Operating system: Mac OS X
2. Phone/emulator/simulator & version: 11

## Reproducible Demo

```
create-react-native-app MyRnApp

```

**Comment by bestander** [comment]
Related to yarnpkg bin, I tried forcing yarn:

```
 create-react-native-app MyRnApp3 --package-manager yarn
Creating a new React Native app in /Users/bestander/work/MyRnApp3.

Using package manager as yarn with yarn interface.
Installing packages. This might take a couple minutes.
Installing react-native-scripts...

MAC
Using globally installed version of Yarn
yarn add v1.2.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning react-native-scripts > xdl > auth0-js > xtend > object-keys@0.4.0:
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-redux@5.0.6" has unmet peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 380 new dependencies.
├─ @expo/bunyan@1.8.10
├─ @expo/json-file@5.3.0
├─ @expo/osascript@1.8.1
├─ @expo/schemer@1.1.0
├─ @expo/spawn-async@1.3.0
├─ @segment/loosely-validate-event@1.1.2
├─ accepts@1.3.4
├─ agent-base@2.1.1
├─ ajv@5.5.2
├─ analytics-node@2.4.1
├─ ansi-escapes@3.0.0
├─ ansi-regex@3.0.0
├─ ansi-styles@3.2.0
├─ any-promise@1.3.0
├─ array-flatten@1.1.1
├─ array-union@1.0.2
├─ array-uniq@1.0.3
├─ asap@2.0.6
├─ asn1@0.2.3
├─ assert-plus@1.0.0
├─ ast-types@0.10.1
├─ async@1.5.2
├─ asynckit@0.4.0
├─ auth0-js@7.6.1
├─ auth0@2.9.1
├─ aws-sign2@0.7.0
├─ aws4@1.6.0
├─ axios@0.16.2
├─ babel-plugin-syntax-flow@6.18.0
├─ babel-plugin-transform-flow-strip-types@6.22.0
├─ babel-polyfill@6.26.0
├─ babel-preset-flow@6.23.0
├─ babel-runtime@6.26.0
├─ balanced-match@1.0.0
├─ base64-js@1.2.0
├─ Base64@0.1.4
├─ base64url@2.0.0
├─ bcrypt-pbkdf@1.0.1
├─ bluebird@2.11.0
├─ body-parser@1.18.2
├─ boom@4.3.1
├─ brace-expansion@1.1.8
├─ buffer-equal-constant-time@1.0.1
├─ bytes@3.0.0
├─ callsite@1.0.0
├─ camel-case@1.2.2
├─ capture-stack-trace@1.0.0
├─ caseless@0.12.0
├─ chalk@2.3.0
├─ change-case@2.3.1
├─ chardet@0.4.2
├─ chownr@1.0.1
├─ cli-cursor@2.1.0
├─ cli-width@2.2.0
├─ clone@2.1.1
├─ co@4.6.0
├─ color-convert@1.9.1
├─ color-name@1.1.3
├─ combined-stream@1.0.5
├─ commander@2.13.0
├─ component-emitter@1.2.1
├─ component-type@1.2.1
├─ concat-map@0.0.1
├─ concat-stream@1.6.0
├─ constant-case@1.1.2
├─ content-disposition@0.5.2
├─ content-type@1.0.4
├─ cookie-signature@1.0.6
├─ cookie@0.3.1
├─ cookiejar@2.1.1
├─ core-js@2.5.3
├─ core-util-is@1.0.2
├─ create-error-class@3.0.2
├─ cross-spawn@5.1.0
├─ cryptiles@3.1.2
├─ crypto-token@1.0.1
├─ dashdash@1.14.1
├─ data-uri-to-buffer@1.2.0
├─ debug@2.6.9
├─ decache@4.3.0
├─ deep-diff@0.3.4
├─ deep-is@0.1.3
├─ deepmerge@1.5.2
├─ define-properties@1.1.2
├─ degenerator@1.0.4
├─ delay-async@1.1.0
├─ delayed-stream@1.0.0
├─ depd@1.1.2
├─ destroy@1.0.4
├─ dot-case@1.1.2
├─ duplexer3@0.1.4
├─ ecc-jsbn@0.1.1
├─ ecdsa-sig-formatter@1.0.9
├─ ee-first@1.1.1
├─ encodeurl@1.0.1
├─ encoding@0.1.12
├─ es-abstract@1.10.0
├─ es-to-primitive@1.1.1
├─ es6-error@4.1.1
├─ es6-promise@4.2.2
├─ es6-promisify@5.0.0
├─ escape-html@1.0.3
├─ escape-string-regexp@1.0.5
├─ escodegen@1.9.0
├─ esprima@3.1.3
├─ estraverse@4.2.0
├─ esutils@2.0.2
├─ etag@1.8.1
├─ exec-async@2.2.0
├─ exists-async@2.0.0
├─ express@4.16.2
├─ extend@3.0.1
├─ external-editor@2.1.0
├─ extsprintf@1.3.0
├─ fast-deep-equal@1.0.0
├─ fast-json-stable-stringify@2.0.0
├─ fast-levenshtein@2.0.6
├─ fbjs@0.8.16
├─ figures@2.0.0
├─ file-type@4.4.0
├─ file-uri-to-path@1.0.0
├─ finalhandler@1.1.0
├─ follow-redirects@1.3.0
├─ foreach@2.0.5
├─ forever-agent@0.6.1
├─ form-data@2.3.1
├─ formidable@1.1.1
├─ forwarded@0.1.2
├─ freeport-async@1.1.1
├─ fresh@0.5.2
├─ fs-extra@3.0.1
├─ fs-minipass@1.2.5
├─ fs.realpath@1.0.0
├─ ftp@0.3.10
├─ function-bind@1.1.1
├─ get-stream@3.0.0
├─ get-uri@2.0.1
├─ getenv@0.7.0
├─ getpass@0.1.7
├─ glob@7.1.2
├─ globby@6.1.0
├─ got@6.7.1
├─ graceful-fs@4.1.11
├─ har-schema@2.0.0
├─ har-validator@5.0.3
├─ has-flag@2.0.0
├─ has-symbols@1.0.0
├─ has@1.0.1
├─ hasbin@1.2.3
├─ hawk@6.0.2
├─ hoek@4.2.0
├─ hoist-non-react-statics@2.3.1
├─ home-dir@1.0.0
├─ http-errors@1.6.2
├─ http-proxy-agent@1.0.0
├─ http-signature@1.2.0
├─ https-proxy-agent@1.0.0
├─ iconv-lite@0.4.19
├─ idx@2.2.0
├─ indent-string@3.2.0
├─ inflight@1.0.6
├─ inherits@2.0.3
├─ inquirer@3.3.0
├─ instapromise@2.0.7-rc.1
├─ invariant@2.2.2
├─ ip@1.1.5
├─ ipaddr.js@1.5.2
├─ is-buffer@1.1.6
├─ is-callable@1.1.3
├─ is-date-object@1.0.1
├─ is-fullwidth-code-point@2.0.0
├─ is-lower-case@1.1.3
├─ is-promise@2.1.0
├─ is-redirect@1.0.0
├─ is-regex@1.0.4
├─ is-retry-allowed@1.1.0
├─ is-stream@1.1.0
├─ is-symbol@1.0.1
├─ is-typedarray@1.0.0
├─ is-upper-case@1.1.2
├─ isarray@1.0.0
├─ isemail@2.2.1
├─ isexe@2.0.0
├─ isomorphic-fetch@2.2.1
├─ isstream@0.1.2
├─ items@2.1.1
├─ joi@10.6.0
├─ join-component@1.1.0
├─ js-tokens@3.0.2
├─ jsbn@0.1.1
├─ json-fallback@0.0.1
├─ json-schema-traverse@0.3.1
├─ json-schema@0.2.3
├─ json-stringify-safe@5.0.1
├─ json5@0.5.1
├─ jsonfile@2.4.0
├─ jsonp@0.0.4
├─ jsonschema@1.2.2
├─ jsonwebtoken@7.4.3
├─ jsprim@1.4.1
├─ jwa@1.1.5
├─ jws@3.1.4
├─ levn@0.3.0
├─ lock@0.1.4
├─ lodash-es@4.17.4
├─ lodash.once@4.1.1
├─ lodash@4.17.4
├─ loose-envify@1.3.1
├─ lower-case-first@1.0.2
├─ lower-case@1.1.4
├─ lowercase-keys@1.0.0
├─ lru-cache@4.1.1
├─ lru-memoizer@1.11.1
├─ lsmod@1.0.0
├─ match-require@2.1.0
├─ md5hex@1.0.0
├─ media-typer@0.3.0
├─ merge-descriptors@1.0.1
├─ methods@1.1.2
├─ mime-db@1.30.0
├─ mime-types@2.1.17
├─ mime@1.4.1
├─ mimic-fn@1.1.0
├─ minimatch@3.0.4
├─ minimist@1.2.0
├─ minipass@2.2.1
├─ minizlib@1.1.0
├─ mkdirp-promise@5.0.1
├─ mkdirp@0.5.1
├─ moment@2.20.1
├─ ms@2.0.0
├─ mute-stream@0.0.7
├─ mv@2.1.1
├─ mz@2.7.0
├─ ncp@2.0.0
├─ negotiator@0.6.1
├─ netmask@1.0.6
├─ next-tick@1.0.0
├─ node-fetch@1.7.3
├─ oauth-sign@0.8.2
├─ object-assign@4.1.1
├─ object-keys@1.0.11
├─ object.assign@4.1.0
├─ object.getownpropertydescriptors@2.0.3
├─ on-finished@2.3.0
├─ once@1.4.0
├─ onetime@2.0.1
├─ opn@4.0.2
├─ optionator@0.8.2
├─ os-tmpdir@1.0.2
├─ pac-proxy-agent@2.0.0
├─ pac-resolver@3.0.0
├─ param-case@1.1.2
├─ parseurl@1.3.2
├─ pascal-case@1.1.2
├─ path-case@1.1.2
├─ path-exists@3.0.0
├─ path-is-absolute@1.0.1
├─ path-to-regexp@0.1.7
├─ performance-now@2.1.0
├─ pify@2.3.0
├─ pinkie-promise@2.0.1
├─ pinkie@2.0.4
├─ plist@2.1.0
├─ prelude-ls@1.1.2
├─ prepend-http@1.0.4
├─ probe-image-size@3.2.0
├─ process-nextick-args@1.0.7
├─ progress@2.0.0
├─ promise@7.3.1
├─ prop-types@15.6.0
├─ proxy-addr@2.0.2
├─ proxy-agent@2.1.0
├─ pseudomap@1.0.2
├─ punycode@1.3.2
├─ qrcode-terminal@0.11.0
├─ qs@6.5.1
├─ querystring@0.2.0
├─ range-parser@1.2.0
├─ raven-js@3.22.0
├─ raven@2.3.0
├─ raw-body@2.3.2
├─ react-native-scripts@1.8.1
├─ react-redux@5.0.6
├─ read-chunk@2.1.0
├─ readable-stream@2.3.3
├─ redux-logger@2.10.2
├─ redux@3.7.2
├─ regenerator-runtime@0.11.1
├─ remove-trailing-slash@0.1.0
├─ replace-string@1.1.0
├─ request-progress@3.0.0
├─ request@2.83.0
├─ reqwest@2.0.5
├─ rest-facade@1.10.1
├─ restore-cursor@2.0.0
├─ retry@0.10.1
├─ rimraf@2.6.2
├─ run-async@2.3.0
├─ rx-lite-aggregates@4.0.8
├─ rx-lite@4.0.8
├─ safe-buffer@5.1.1
├─ safe-json-stringify@1.0.4
├─ semver@5.0.3
├─ send@0.16.1
├─ sentence-case@1.1.3
├─ serve-static@1.13.1
├─ setimmediate@1.0.5
├─ setprototypeof@1.1.0
├─ shebang-command@1.2.0
├─ shebang-regex@1.0.0
├─ signal-exit@3.0.2
├─ slugid@1.1.0
├─ slugify@1.2.9
├─ smart-buffer@1.1.15
├─ snake-case@1.1.2
├─ sntp@2.1.0
├─ socks-proxy-agent@2.1.1
├─ socks@1.1.10
├─ source-map-support@0.4.18
├─ source-map@0.5.7
├─ sshpk@1.13.1
├─ stack-trace@0.0.9
├─ statuses@1.3.1
├─ stream-parser@0.3.1
├─ string_decoder@1.0.3
├─ string-width@2.1.1
├─ stringstream@0.0.5
├─ strip-ansi@4.0.0
├─ superagent-proxy@1.0.2
├─ superagent-retry@0.6.0
├─ superagent@3.8.2
├─ supports-color@4.5.0
├─ swap-case@1.1.2
├─ symbol-observable@1.1.0
├─ tar@4.2.0
├─ thenify-all@1.6.0
├─ thenify@3.3.0
├─ throttleit@1.0.0
├─ through@2.3.8
├─ thunkify@2.1.2
├─ timed-out@4.0.1
├─ title-case@1.1.2
├─ tmp@0.0.33
├─ topo@2.0.2
├─ tough-cookie@2.3.3
├─ tree-kill@1.2.0
├─ trim@0.0.1
├─ tunnel-agent@0.6.0
├─ tweetnacl@0.14.5
├─ type-check@0.3.2
├─ type-is@1.6.15
├─ typedarray@0.0.6
├─ ua-parser-js@0.7.17
├─ universalify@0.1.1
├─ unpipe@1.0.0
├─ unzip-response@2.0.1
├─ upper-case-first@1.1.2
├─ upper-case@1.1.3
├─ url-parse-lax@1.0.0
├─ url@0.11.0
├─ util-deprecate@1.0.2
├─ util.promisify@1.0.0
├─ utils-merge@1.0.1
├─ uuid@3.1.0
├─ vary@1.1.2
├─ verror@1.10.0
├─ very-fast-args@1.1.0
├─ whatwg-fetch@2.0.3
├─ which@1.3.0
├─ winchan@0.1.4
├─ wordwrap@1.0.0
├─ wrappy@1.0.2
├─ xdl@47.0.4
├─ xmlbuilder@8.2.2
├─ xmldom@0.1.27
├─ xregexp@2.0.0
├─ xtend@4.0.1
├─ yallist@2.1.2
└─ yesno@0.0.1
✨  Done in 10.43s.
Installing dependencies using yarn...

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarnpkg ENOENT
    at exports._errnoException (util.js:1016:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

I suppose a way around this is to add yarnpkg bin to my PATH

**Comment by bestander** [comment]
And here is the final workaround if you have yarn but create-react-native-app does not find it:
```
sudo cp $(which yarn) $(which yarn)pkg
```

**Comment by brentvatne** [comment]
cc @fson

**Comment by fson** [comment]
@bestander out of curiosity, which installation method did you use to install Yarn? If the alias is not there, maybe this should be reported to the Yarn team or the author of the distribution package you're using.

The reason we use `yarnpkg` instead of `yarn` executable is, IIRC, that the Hadoop project includes also a command named `yarn` and this was falsely detected as Yarn for some people. The `yarnpkg` alias is more unique. But if there are Yarn installations without the alias, then we might have to rethink that strategy.

When it comes to the npm 5 error, I hope we'll be able to remove it soon enough.

**Comment by bestander** [comment]
Yeah, after thinking about this it makes sense that it would be easier to
expose yarnpkg binary in all yarn installations.
I think I used an install script, not brew.

I’ll try to open a PR in yarn to add yanrpkg bin

**Comment by bestander** [comment]
Hm weird, yarnpkg binary is in the bin folder https://github.com/yarnpkg/yarn/tree/master/bin

**Comment by bestander** [comment]
Yeah, looks like this was because my local setup has only `yarn` bin exposed to PATH.
I checked brew and install script expose both yarn and yarnpkg.

I'll close the task
