### ISSUE TITLE
react-native run-android gives error Cannot find module '@babel/core'

### ISSUE THREAD

**Issue by p-sheth** [react-community/create-react-native-app#641]
I tried to eject to build APK on windows machine.
eject failed with error "Can not delete node_modules\....The directory is not empty"

After that I am stuck,
1. eject does not work anymore. I get error eject script not found.
2. react-native run-android gives error
Cannot find module '@babel/core'
3. npm start gives error
Cannot find module '@babel/core'

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: `-- (empty)
* `npm ls react-native`: `-- react-native@0.54.0
* `npm ls expo`: ``-- (empty)
* `node -v`: v8.10.0
* `npm -v`: 5.6.0
* `yarn --version`: 1.6.0
* `watchman version`:

1. Operating system: Windows 10
2. Phone/emulator/simulator & version: Motorola X Play - Android 7.1.1

I tried reinstalling babel core , didn't help

**Comment by esamelson** [comment]
Hi @p-sheth  - have you tried totally clearing away your `node_modules` and reinstalling them?

**Comment by p-sheth** [comment]
After reinstalling node_modules, Metro bundler throws error while running on Android:

Metro Bundler ready.

Loading dependency graph, done.
error: bundling failed: Error: Couldn't find preset "babel-preset-react-native-stage-0/decorator-support" relative to directory "D:\\dev\\bhagvatgita"
    at D:\dev\bhagvatgita\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (D:\dev\bhagvatgita\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (D:\dev\bhagvatgita\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (D:\dev\bhagvatgita\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (D:\dev\bhagvatgita\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (D:\dev\bhagvatgita\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (D:\dev\bhagvatgita\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (D:\dev\bhagvatgita\node_modules\babel-core\lib\transformation\pipeline.js:46:16)

**Comment by Gash21** [comment]
@p-sheth this happened to me today, fixed by this [react-native/issues/15545](https://github.com/facebook/react-native/issues/15545#issuecomment-357099224)
