### ISSUE TITLE
iOS simulator doesn't initially work after ejecting a "create-react-native-app --with-web-support"-app

### ISSUE THREAD

**Issue by sanderlooijenga** [react-community/create-react-native-app#683]
## Description
When creating a react native app with the command `create-react-native-app` and with argument `--with-web-support` and then `reject`ing it, the `npm run ios` won't startup the simulator successfully.

**NOTE:** See PR (+comment); https://github.com/react-community/create-react-native-app/pull/599#issuecomment-397241957

## Expected Behavior
Expected the iOS simulator to start when running `npm run ios` (as it does when running `create-react-native-app --with-web-support` **without** ejecting it).

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
error: bundling failed: Error: Unable to resolve module `./App` from `/Users/sanderlooijenga/Projects/Work/AwesomeProjectV2-ejected/index.js`: The module `./App` could not be found from `/Users/sanderlooijenga/Projects/Work/AwesomeProjectV2-ejected/index.js`. Indeed, none of these files exist:

  * `/Users/sanderlooijenga/Projects/Work/AwesomeProjectV2-ejected/App(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/Users/sanderlooijenga/Projects/Work/AwesomeProjectV2-ejected/App/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
    at ModuleResolver.resolveDependency (/Users/sanderlooijenga/Projects/Work/AwesomeProjectV2-ejected/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:161:851)
    at ResolutionRequest.resolveDependency (/Users/sanderlooijenga/Projects/Work/AwesomeProjectV2-ejected/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:91:16)
    at DependencyGraph.resolveDependency (/Users/sanderlooijenga/Projects/Work/AwesomeProjectV2-ejected/node_modules/metro/src/node-haste/DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (/Users/sanderlooijenga/Projects/Work/AwesomeProjectV2-ejected/node_modules/metro/src/DeltaBundler/traverseDependencies.js:376:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/sanderlooijenga/Projects/Work/AwesomeProjectV2-ejected/node_modules/metro/src/DeltaBundler/traverseDependencies.js:374:16)
    at /Users/sanderlooijenga/Projects/Work/AwesomeProjectV2-ejected/node_modules/metro/src/DeltaBundler/traverseDependencies.js:212:33
    at Generator.next (<anonymous>)
    at step (/Users/sanderlooijenga/Projects/Work/AwesomeProjectV2-ejected/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:313)
    at /Users/sanderlooijenga/Projects/Work/AwesomeProjectV2-ejected/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:473
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: `(empty)`
* `npm ls react-native`: `react-native@0.55.4`
* `npm ls expo`: `(empty)`
* `node -v`: `v8.11.2`
* `npm -v`: `5.6.0`
* `yarn --version`: `1.7.0`
* `watchman version`: `4.9.0`

Also specify:

1. Operating system: `macOS High Sierra - Version 10.13.4 (17E199)`
2. Phone/emulator/simulator & version: Xcode Emulator`iPhone 6 - 11.4`

## Reproducible Demo

1. `create-react-native-app my-ejected-web-app --with-web-support`
2. `npm run eject` (when asked **_"How would you like to eject from create-react-native-app?"_** -> **_"React Native: I'd like a regular React Native project."_**
3. `npm run ios`

**Comment by soranoba** [comment]
Hi, @sanderlooijenga 
Have you solved this problem already?

I also encountered the same problem and resolved, so I share the solution.
FYI.

```diff
diff --git a/android/app/build.gradle b/android/app/build.gradle
index fc0be71..fd1f85d 100644
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -73,7 +73,7 @@ import com.android.build.OutputFile
  */
 
 project.ext.react = [
-    entryFile: "index.js"
+    entryFile: "src/index.native.js"
 ]
 
 apply from: "../../node_modules/react-native/react.gradle"
diff --git a/android/app/src/main/java/com/reactnativeskelton/MainApplication.java b/android/app/src/main/java/com/reactnativeskelton/MainApplication.java
index b3180a4..f162132 100644
--- a/android/app/src/main/java/com/reactnativeskelton/MainApplication.java
+++ b/android/app/src/main/java/com/reactnativeskelton/MainApplication.java
@@ -28,7 +28,7 @@ public class MainApplication extends Application implements ReactApplication {
 
     @Override
     protected String getJSMainModuleName() {
-      return "index";
+      return "src/index.native";
     }
   };
 
diff --git a/ios/ReactNativeSkelton/AppDelegate.m b/ios/ReactNativeSkelton/AppDelegate.m
index 66837d7..fcfb143 100644
--- a/ios/ReactNativeSkelton/AppDelegate.m
+++ b/ios/ReactNativeSkelton/AppDelegate.m
@@ -16,7 +16,7 @@
 {
   NSURL *jsCodeLocation;
 
-  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
+  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"src/index.native" fallbackResource:nil];
 
   RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                       moduleName:@"ReactNativeSkelton"
diff --git a/index.js b/src/index.native.js
similarity index 100%
rename from index.js
rename to src/index.native.js
```

![2018-07-30 16 51 55](https://user-images.githubusercontent.com/4954289/43384405-ec5949f2-9418-11e8-9aab-7403ba646dab.png)

**Comment by hushicai** [comment]
I am can not eject a app created with `with-web-support`.

missing index.native and index.js is like this:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';

ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
```
