### ISSUE TITLE
create-react-native-app unable to start

### ISSUE THREAD

**Issue by w-pittman** [react-community/create-react-native-app#684]
## Description

I am trying to run create-react-native-app and am getting the following error:
npm ERR! cb() never called!

## Expected Behavior

I ran the appropriate command and expected my react-native project to be created successfully.

## Observed Behavior

After create-react-native-app test4, I got the following errors:

```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wpittman\AppData\Roaming\npm-cache\_logs\2018-06-16T17_42_37_187Z-debug.log


****After npm start in test4 directory:******
 test4@0.1.0 start C:\Users\wpittman\react-native\test4
> react-native-scripts start

12:45:15 PM: Starting packager...
***ERROR STARTING PACKAGER***

Error: React native is not installed. Please run `npm install` in your project directory.
12:45:22 PM: Error starting packager: Error: Couldn't start project. Please fix the errors and restart the project.
    at C:\xdl\src\Project.js:1329:11
    at next (native)
    at step (C:\Users\wpittman\react-native\test4\node_modules\xdl\build\Project.js:1735:191)
    at C:\Users\wpittman\react-native\test4\node_modules\xdl\build\Project.js:1735:361
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test4@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test4@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wpittman\AppData\Roaming\npm-cache\_logs\2018-06-16T17_45_22_532Z-debug.log
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: -- react-native-scripts@1.14.0
* `npm ls react-native`: -- react-native@0.55.4
* `npm ls expo`:`-- UNMET DEPENDENCY expo@^27.0.1

npm ERR! missing: expo@^27.0.1, required by test4@0.1.0
* `node -v`: v6.11.5
* `npm -v`: 4.6.1
* `yarn --version`: 
* `watchman version`:

Also specify:

1. Operating system: WIndows

**Comment by brentvatne** [comment]
see the error msg:

```
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by roushanj** [comment]
Try ------- $ npm clean cache --force
It worked for me

**Comment by nnvn** [comment]
@roushanj you mean, npm **cache** _clean_ --force
