### ISSUE TITLE
Running `create-react-native-app myApp` and `npm start` errors but is resolved by doing a manual npm install

### ISSUE THREAD

**Issue by nylki** [react-community/create-react-native-app#693]
## Description

Running `create-react-native-app AwsomeApp` finished with an error. Running `npm start` afterwards results in further errors, and not starting the actual app.

## Observed Behavior

When running create-react-native-app I get an error, seen below. Ignoring that and continuing to `cd AwsomeProject` and `npm start` it says:
> Error: React native is not installed. Please run 'npm install' in your project directory.

Doing a manual `npm install`, as advised in the terminal output and then running `npm start` works fine though, giving me the QR-code and everything.

Here is my full terminal dump:
```.sh
➜  react-native-experiments create-react-native-app AwesomeProject
Creating a new React Native app in /home/tom/Programming/react-native-experiments/AwesomeProject.

Using package manager as npm with npm interface.
Installing packages. This might take a couple minutes.
Installing react-native-scripts...

npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-darwin-x64@2.2.8 (node_modules/@expo/ngrok-bin-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-darwin-x64@2.2.8: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-freebsd-ia32@2.2.8 (node_modules/@expo/ngrok-bin-freebsd-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-freebsd-ia32@2.2.8: wanted {"os":"freebsd","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-darwin-ia32@2.2.8 (node_modules/@expo/ngrok-bin-darwin-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-darwin-ia32@2.2.8: wanted {"os":"darwin","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-freebsd-x64@2.2.8 (node_modules/@expo/ngrok-bin-freebsd-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-freebsd-x64@2.2.8: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-arm@2.2.8 (node_modules/@expo/ngrok-bin-linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-arm@2.2.8: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-arm64@2.2.8 (node_modules/@expo/ngrok-bin-linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-arm64@2.2.8: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-ia32@2.2.8 (node_modules/@expo/ngrok-bin-linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-ia32@2.2.8: wanted {"os":"linux","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-sunos-x64@2.2.8 (node_modules/@expo/ngrok-bin-sunos-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-sunos-x64@2.2.8: wanted {"os":"sunos","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-win32-ia32@2.2.8-beta.1 (node_modules/@expo/ngrok-bin-win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-win32-ia32@2.2.8-beta.1: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-win32-x64@2.2.8-beta.1 (node_modules/@expo/ngrok-bin-win32-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-win32-x64@2.2.8-beta.1: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})

+ react-native-scripts@1.14.0
added 442 packages from 477 contributors and audited 1178 packages in 27.988s
found 2 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
Installing dependencies using yarn...

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarnpkg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
➜  react-native-experiments cd AwesomeProject 
➜  AwesomeProject npm start

> AwesomeProject@0.1.0 start /home/tom/Programming/react-native-experiments/AwesomeProject
> react-native-scripts start

10:45:37: Starting packager...
***ERROR STARTING PACKAGER***

Error: React native is not installed. Please run `npm install` in your project directory.
10:45:40: Error starting packager: Error: Couldn't start project. Please fix the errors and restart the project.
    at /xdl/src/Project.js:1329:11
    at Generator.next (<anonymous>)
    at step (/home/tom/Programming/react-native-experiments/AwesomeProject/node_modules/xdl/build/Project.js:1735:191)
    at /home/tom/Programming/react-native-experiments/AwesomeProject/node_modules/xdl/build/Project.js:1735:361
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! AwesomeProject@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the AwesomeProject@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tom/.npm/_logs/2018-06-27T08_45_40_571Z-debug.log
➜  AwesomeProject 
```

Here is the output of npm's debug log:
```.sh
cat /home/tom/.npm/_logs/2018-06-27T08_45_40_571Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/home/tom/.nvm/versions/node/v10.4.0/bin/node',
1 verbose cli   '/home/tom/.nvm/versions/node/v10.4.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.1.0
3 info using node@v10.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle AwesomeProject@0.1.0~prestart: AwesomeProject@0.1.0
6 info lifecycle AwesomeProject@0.1.0~start: AwesomeProject@0.1.0
7 verbose lifecycle AwesomeProject@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle AwesomeProject@0.1.0~start: PATH: /home/tom/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/tom/Programming/react-native-experiments/AwesomeProject/node_modules/.bin:/home/tom/bin/zotero:/home/tom/torch/install/bin:/home/tom/bin:/usr/local/bin:/home/tom/.nvm/versions/node/v10.4.0/bin:/home/tom/bin:/home/tom/.local/bin:/home/tom/node_modules/bin:/usr/lib64/qt-3.3/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/tom/bin:/home/tom/AndroidSDK:/home/tom/AndroidSDK/tools:/home/tom/AndroidSDK/platform-tools:/home/tom/dotnet:/home/tom/.cargo/bin
9 verbose lifecycle AwesomeProject@0.1.0~start: CWD: /home/tom/Programming/react-native-experiments/AwesomeProject
10 silly lifecycle AwesomeProject@0.1.0~start: Args: [ '-c', 'react-native-scripts start' ]
11 silly lifecycle AwesomeProject@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle AwesomeProject@0.1.0~start: Failed to exec start script
13 verbose stack Error: AwesomeProject@0.1.0 start: `react-native-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/tom/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/tom/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid AwesomeProject@0.1.0
15 verbose cwd /home/tom/Programming/react-native-experiments/AwesomeProject
16 verbose Linux 4.17.2-200.fc28.x86_64
17 verbose argv "/home/tom/.nvm/versions/node/v10.4.0/bin/node" "/home/tom/.nvm/versions/node/v10.4.0/bin/npm" "start"
18 verbose node v10.4.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error AwesomeProject@0.1.0 start: `react-native-scripts start`
22 error Exit status 1
23 error Failed at the AwesomeProject@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
Here is the output of npm audit in the created project:
```.sh
➜  AwesomeProject npm audit
npm ERR! code ELOCKVERIFY
npm ERR! Errors were found in your package-lock.json, run  npm install  to fix them.
npm ERR!     Missing: expo@^27.0.1
npm ERR!     Invalid: lock file's react@16.4.1 does not satisfy react@16.3.1
npm ERR!     Missing: react-native@~0.55.2
npm ERR!     Missing: jest-expo@~27.0.0
npm ERR!     Missing: react-test-renderer@16.3.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tom/.npm/_logs/2018-06-27T08_56_51_421Z-debug.log
```

## Environment

* `npm ls react-native-scripts`: 1.14.0
* `npm ls react-native`: npm ERR! missing: react-native@~0.55.2
* `npm ls expo`: pm ERR! missing: expo@^27.0.1
* `node -v`: v10.4.0
* `npm -v`: 6.1.0
* `yarn --version`: n/a
* `watchman version`: n/a

1. Operating system: Fedora 28.
2. (not relevant for this issue)

## Reproducible Demo
`npm install -g create-react-native-app && create-react-native-app AwsomeProject && cd AwsomeProject && npm start`

**Comment by nylki** [comment]
@fson I can still reproduce the issue.
The `node_modules` directory _does_ exist.
However `node_modules/react-native` is missing. Here is my full `ls` output:

```.sh
➜  AwesomeProject ls node_modules 
accepts                                  define-properties           idx                      netmask                           setimmediate
agent-base                               degenerator                 indent-string            next-tick                         setprototypeof
ajv                                      delay-async                 inflight                 node-fetch                        shebang-command
analytics-node                           delayed-stream              inherits                 oauth-sign                        shebang-regex
ansi-escapes                             depd                        inquirer                 object-assign                     signal-exit
ansi-regex                               destroy                     instapromise             object.assign                     slugid
ansi-styles                              dot-case                    invariant                object.getownpropertydescriptors  slugify
any-promise                              duplexer3                   ip                       object-keys                       smart-buffer
array-flatten                            ecc-jsbn                    ipaddr.js                once                              snake-case
array-union                              ecdsa-sig-formatter         isarray                  onetime                           socks
array-uniq                               ee-first                    is-buffer                on-finished                       socks-proxy-agent
asap                                     encodeurl                   is-callable              opn                               source-map
asn1                                     encoding                    is-date-object           optionator                        source-map-support
assert-plus                              es6-error                   isemail                  os-tmpdir                         split
ast-types                                es6-promise                 isexe                    pac-proxy-agent                   sshpk
async                                    es6-promisify               is-fullwidth-code-point  pac-resolver                      stack-trace
asynckit                                 es-abstract                 is-lower-case            param-case                        statuses
auth0                                    escape-html                 isomorphic-fetch         parseurl                          stealthy-require
auth0-js                                 escape-string-regexp        is-promise               pascal-case                       stream-parser
aws4                                     escodegen                   is-redirect              path-case                         string_decoder
aws-sign2                                esprima                     is-regex                 path-exists                       string-width
axios                                    es-to-primitive             is-retry-allowed         path-is-absolute                  strip-ansi
babel-plugin-syntax-flow                 estraverse                  is-stream                path-to-regexp                    superagent
babel-plugin-transform-flow-strip-types  esutils                     isstream                 performance-now                   superagent-proxy
babel-polyfill                           etag                        is-symbol                pify                              superagent-retry
babel-preset-flow                        exec-async                  is-typedarray            pinkie                            supports-color
babel-runtime                            exists-async                is-upper-case            pinkie-promise                    swap-case
balanced-match                           @expo                       items                    plist                             symbol-observable
base64-js                                express                     joi                      prelude-ls                        tar
bcrypt-pbkdf                             extend                      join-component           prepend-http                      thenify
bluebird                                 external-editor             jsbn                     probe-image-size                  thenify-all
body-parser                              extsprintf                  json5                    process-nextick-args              throttleit
brace-expansion                          fast-deep-equal             jsonfile                 progress                          through
buffer-equal-constant-time               fast-json-stable-stringify  json-schema              promise                           thunkify
buffer-from                              fast-levenshtein            jsonschema               prop-types                        timed-out
bytes                                    fbjs                        json-schema-traverse     proxy-addr                        title-case
callsite                                 figures                     json-stringify-safe      proxy-agent                       tmp
camel-case                               file-type                   jsonwebtoken             proxy-from-env                    topo
capture-stack-trace                      file-uri-to-path            jsprim                   pseudomap                         tough-cookie
caseless                                 finalhandler                js-tokens                punycode                          tree-kill
chalk                                    follow-redirects            jwa                      qrcode-terminal                   tunnel-agent
change-case                              foreach                     jws                      qs                                tweetnacl
chardet                                  forever-agent               levn                     querystring                       type-check
charenc                                  form-data                   lock                     range-parser                      typedarray
chownr                                   formidable                  lodash                   raven                             type-is
cli-cursor                               forwarded                   lodash-es                raven-js                          @types
cli-width                                freeport-async              lodash.once              raw-body                          ua-parser-js
clone                                    fresh                       logfmt                   react                             universalify
co                                       fs-extra                    loose-envify             react-native-scripts              unpipe
color-convert                            fs-minipass                 lower-case               react-redux                       unzip-response
color-name                               fs.realpath                 lower-case-first         readable-stream                   upper-case
combined-stream                          ftp                         lowercase-keys           read-chunk                        upper-case-first
commander                                function-bind               lru-cache                redux                             url
component-emitter                        getenv                      lru-memoizer             redux-logger                      url-join
component-type                           getpass                     match-require            regenerator-runtime               url-parse-lax
concat-map                               get-stream                  md5                      remove-trailing-slash             util-deprecate
concat-stream                            get-uri                     md5hex                   replace-string                    util.promisify
constant-case                            glob                        media-typer              request                           utils-merge
content-disposition                      globby                      merge-descriptors        request-progress                  uuid
content-type                             glob-promise                methods                  request-promise-core              vary
cookie                                   got                         mime                     request-promise-native            verror
cookiejar                                graceful-fs                 mime-db                  rest-facade                       very-fast-args
cookie-signature                         har-schema                  mime-types               restore-cursor                    whatwg-fetch
core-js                                  har-validator               mimic-fn                 retry                             which
core-util-is                             has                         minimatch                rimraf                            winchan
create-error-class                       hasbin                      minimist                 run-async                         wordwrap
cross-spawn                              has-flag                    minipass                 rxjs                              wrappy
crypt                                    has-symbols                 minizlib                 rx-lite                           xdl
crypto-js                                hoek                        mkdirp                   rx-lite-aggregates                xmlbuilder
crypto-token                             hoist-non-react-statics     mkdirp-promise           safe-buffer                       xmldom
dashdash                                 home-dir                    moment                   safe-json-stringify               xregexp
data-uri-to-buffer                       http-errors                 ms                       safer-buffer                      xtend
debug                                    http-proxy-agent            mute-stream              @segment                          yallist
decache                                  http-signature              mv                       semver                            yesno
deep-diff                                https-proxy-agent           mz                       send
deep-is                                  iconv-lite                  ncp                      sentence-case
deepmerge                                idtoken-verifier            negotiator               serve-static

```

**Comment by nylki** [comment]
It appears like some install script of a dependency return with an error, thereby letting `npm` error? Also this line in seems unusual:
```.sh
Installing dependencies using yarn...

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarnpkg ENOENT
```
I do not have yarn installed and would not expect it to be necessary. But it appears to be related, if I would take a guess.

**Comment by jamachad** [comment]
@nylki , I had this also and it was fixed after I upgraded the npm version.

I ran the following **npm install -g npm@latest**  

[More commands for npm upgrade](https://docs.npmjs.com/troubleshooting/try-the-latest-stable-version-of-npm)

**Comment by nylki** [comment]
@jamachad What is your actual npm version?
Because I updated npm to the latest version just a few days ago, if I remember correctly.

**Comment by jamachad** [comment]
I ended up with 6.1.0 also. I don't think it's the same issue in the end, mine was npm that was closing the connection right after unsupported platform message. Sorry for that.

**Comment by kaitlynbrown** [comment]
I'm seeing the exact same problem. Tried with both 6.1.0 and 6.2.0. When I do have yarn installed, I get a different error.
