### ISSUE TITLE
SyntaxError in package.json

### ISSUE THREAD

**Issue by xavierartot** [react-community/create-react-native-app#762]
I tried to add `yarn add react-navigation` I got this message

```
$ react-native-scripts start
22:22:24: Starting packager...
***ERROR STARTING PACKAGER***

Error parsing JSON file: SyntaxError: Expected '}' instead of '"' at line 7 column 5 of the JSON5 data. Still to read: "\"version\":\"1.0.0\",\n "
22:22:27: Error starting packager: Error: Couldn't start project. Please fix the errors and restart the project.
    at /xdl/src/Project.js:1329:11
    at Generator.next (<anonymous>)
    at step (/Applications/MAMP/htdocs/nanodegree/react-native/FlashCards/node_modules/xdl/build/Project.js:1735:191)
    at /Applications/MAMP/htdocs/nanodegree/react-native/FlashCards/node_modules/xdl/build/Project.js:1735:361
    at <anonymous>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Environment

Please run these commands in the project folder and fill in their results:

➜  FlashCards npm ls react-native-scripts
toto@0.1.0 /Applications/MAMP/htdocs/nanodegree/react-native/FlashCards
└── react-native-scripts@1.14.0

➜  FlashCards npm ls react-native
toto@0.1.0 /Applications/MAMP/htdocs/nanodegree/react-native/FlashCards
└── react-native@0.55.4

➜  FlashCards npm ls expo
toto@0.1.0 /Applications/MAMP/htdocs/nanodegree/react-native/FlashCards
└── expo@27.1.1

```
➜  FlashCards node -v
v8.11.4
➜  FlashCards npm -v
5.6.0
➜  FlashCards yarn --version
1.3.2
➜  FlashCards watchman version
{
    "version": "4.9.0"
}
➜  FlashCards exp --version
57.1.3
➜  FlashCards
```

Also specify:

1. Operating system: Mac osx - High Sierra
2. Phone/emulator/simulator & version:

**Comment by xavierartot** [comment]
I re-create a new project and it works!
